---
- name: "Add entry" # noqa no-tabs
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ item.key }}.{{ hosts_override_local_domain }}"
    line: "{{ item.value }}	{{ item.key }}.{{ hosts_override_local_domain }} {{ item.key }}"
  loop: "{{ hosts_override_add | dict2items }}"

- name: "Remove entry"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ item.key }}.{{ hosts_override_local_domain }}"
    state: absent
  loop: "{{ hosts_override_remove | dict2items }}"

  # when ansible_hostname != item.key could be used if this should not deploy the host entry self
