---

- name: "ensure some internal hosts can be found on external hosts"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ item.key }}.{{ basic.local_domain }}"
    line: "{{ item.value }}      {{ item.key }}.{{ basic.local_domain }} {{ item.key }}"
  loop: "{{ hosts_override_internal | dict2items }}"

  # when ansible_hostname != item.key could be used if this should not deploy the host entry self
